server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**

        - id: account-service
          uri: http://account-service:8086
          predicates:
            - Path=/api/account/**
          filters:
            - JwtAuthFilter